password: letmein

garage.s3:
  allowlist: # Comma separated list of allowed buckets and keys for S3 access.
    bucket:
      - bucket1
      - bucket2
    keys:
      - list
      - of
      - keys
    prefixes:
      - key
      - prefixes
      - allowed
  endpoint:
    local: http://localhost:3900
    remote: https://garage.domain.com # Configure based on your domain name. I use HAProxy for https, who knows if this is optimal

spring:
  application:
    name: classless-wow-web-server

  docker:
    compose:
      enabled: false
  
  # JPA/Hibernate Configuration
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3307/acore_auth
      username: web_server
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    sqlite:
      url: jdbc:sqlite:recovery.db
      driver-class-name: org.sqlite.JDBC

  jpa:
    mysql:
      database-platform: org.hibernate.dialect.MySQL8Dialect
    sqlite:
      database-platform: org.hibernate.community.dialect.SQLiteDialect

server:
  ssl:
    enabled: true
    key-store: classpath:local-keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit
  port: 8443

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: WARN