password: letmein

garage.s3:
  allowlist: # Comma separated list of allowed buckets and keys for S3 access.
    bucket:
      - bucket1
      - bucket2
    keys:
      - list
      - of
      - keys
    prefixes:
      - key
      - prefixes
      - allowed
  endpoint:
    local: http://localhost:3900
    # Garage doesn't support TLS termination at the node level yet, so we have to use a proxy like HAProxy to handle TLS termination
    remote: https://garage.domain.com

launcherservice:
  cacheDir: src/main/resources/static/cache # must match static-locations in spring.web.resources.static-locations
  launcherName: ClasslessLauncher.zip

spring:
  profiles:
    active: "prod" # dev or prod. Prod is mysql db, dev is
  application:
    name: classless-wow-web-server
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:src/main/resources/static/cache # must match cacheDir above

  # JPA/Hibernate Configuration
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3307/acore_auth
      # You must create these users accepting this server's IP address with the roles of 'SELECT', 'INSERT', 'UPDATE' on the database
      username: web_server
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    sqlite:
      url: jdbc:sqlite:recovery.db
      driver-class-name: org.sqlite.JDBC

  jpa:
    mysql:
      database-platform: org.hibernate.dialect.MySQL8Dialect
    sqlite:
      database-platform: org.hibernate.community.dialect.SQLiteDialect

# If you're not behind some other SSL connection leg like a connection to HAProxy (or other load balancer), you must configure SSL here
server:
  port: 8080
  ssl:
    enabled: false

#server:
#  ssl:
#    enabled: true
#    key-store: classpath:local-keystore.p12
#    key-store-type: PKCS12
#    key-store-password: changeit
#  port: 8443

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: WARN